# Generated by Django 5.2.5 on 2025-09-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Ad Slider', max_length=255)),
            ],
            options={
                'verbose_name': 'Рекламный слайдер',
                'verbose_name_plural': 'Рекламные слайдеры',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_text_primary', models.TextField(blank=True, default='', help_text='Геро-текст №1. Перенос строки через Enter')),
                ('hero_text_secondary', models.TextField(blank=True, default='', help_text='Геро-текст №2. Перенос строки через Enter')),
                ('hero_bg_image', models.ImageField(blank=True, null=True, upload_to='homepage/bg/%Y/%m/%d')),
                ('cities_section_title', models.CharField(blank=True, default='', max_length=255)),
                ('activities_section_title', models.CharField(blank=True, default='', max_length=255)),
                ('actions_section_title', models.CharField(blank=True, default='', max_length=255)),
                ('cta_title', models.CharField(blank=True, default='', max_length=255)),
                ('cta_hero_text', models.TextField(blank=True, default='', help_text='Текст над карточкой. Перенос строки через Enter')),
                ('cta_bg_image', models.ImageField(blank=True, null=True, upload_to='homepage/cta_bg/%Y/%m/%d')),
                ('cta_overlay_image', models.ImageField(blank=True, null=True, upload_to='homepage/cta_overlay/%Y/%m/%d')),
                ('cta_card_image', models.ImageField(blank=True, null=True, upload_to='homepage/cta/%Y/%m/%d')),
                ('cta_card_title', models.CharField(blank=True, default='', max_length=255)),
                ('cta_card_description', models.CharField(blank=True, default='', max_length=255)),
                ('cta_button_label', models.CharField(blank=True, default='', max_length=100)),
                ('cta_button_href', models.CharField(blank=True, default='', max_length=255)),
                ('activities_bg_image', models.ImageField(blank=True, null=True, upload_to='homepage/bg/%Y/%m/%d')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_url', models.CharField(blank=True, default='', max_length=255)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='homepage/seo/og/%Y/%m/%d')),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.TextField(blank=True, default='')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='homepage/seo/twitter/%Y/%m/%d')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Главная страница (данные)',
                'verbose_name_plural': 'Главная страница (данные)',
            },
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt', models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=255)),
                ('image', models.ImageField(help_text='Файл изображения', upload_to='uploads/%Y/%m/%d')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='adslider/images/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='adslider/videos/%Y/%m/%d')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cms.adslider')),
            ],
            options={
                'verbose_name': 'Слайд рекламного слайдера',
                'verbose_name_plural': 'Слайды рекламного слайдера',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='homepage/cities/%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Город (карточка)',
                'verbose_name_plural': 'Города (карточки)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='homepage/activities/%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('href', models.CharField(help_text='Ссылка внутри сайта, например /parties', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_buttons', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Кнопка (действие)',
                'verbose_name_plural': 'Кнопки (действия)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePopupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('about', 'Об Абхазии'), ('activities', 'Чем заняться'), ('booking', 'Запланируйте поездку'), ('essentials', 'Необходимо в поездке')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_items', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Пункт всплывающего меню',
                'verbose_name_plural': 'Пункты всплывающего меню',
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/slider/images/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='homepage/slider/videos/%Y/%m/%d')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('about', 'Об Абхазии'), ('activities', 'Чем заняться'), ('booking', 'Запланируйте поездку'), ('essentials', 'Необходимо в поездке')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('href', models.CharField(blank=True, default='', max_length=255)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Таб (верхнее меню)',
                'verbose_name_plural': 'Табы (верхнее меню)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
