# Generated by Django 5.2.6 on 2025-09-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_citiespage_alter_abkhaziancustomspage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('url', models.CharField(help_text='Полная или относительная ссылка, например /administrative-buildings/Sukhum', max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна (кликабельна)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cms.city')),
            ],
            options={
                'verbose_name': 'Категория города',
                'verbose_name_plural': 'Категории города',
                'ordering': ['order', 'id'],
            },
        ),
    ]
