# Generated by Django 5.2.6 on 2025-09-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_dictionarycategory_split_two_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='excursions/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=60)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, upload_to='excursions/twitter/')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница экскурсий',
                'verbose_name_plural': 'Страница экскурсий',
            },
        ),
        migrations.CreateModel(
            name='ExcursionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='excursions/logos/')),
                ('contacts', models.CharField(max_length=255)),
                ('site', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cms.excursionspage')),
            ],
            options={
                'verbose_name': 'Сервис экскурсий',
                'verbose_name_plural': 'Сервисы экскурсий',
                'ordering': ['order', 'id'],
            },
        ),
    ]
