# Generated by Django 5.2.6 on 2025-09-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_hotspringspage_hero_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Важно знать', help_text='Заголовок страницы', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='SEO заголовок', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO описание')),
            ],
            options={
                'verbose_name': "Страница 'Важно знать'",
                'verbose_name_plural': "Страница 'Важно знать'",
            },
        ),
        migrations.CreateModel(
            name='ImportantSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('tourist-pharmacy', 'Туристическая аптечка'), ('emergency-phones', 'Телефоны экстренной помощи'), ('public-behavior', 'Правила поведения в общественных местах'), ('taxi-etiquette', 'Такси-этикет')], help_text='Тип секции', max_length=50)),
                ('title', models.CharField(help_text='Заголовок секции', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Содержимое секции')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.importantpage')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImportantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('passenger', 'Правила для пассажиров'), ('driver', 'Правила для водителей')], help_text='Тип правила', max_length=20)),
                ('title', models.CharField(help_text='Заголовок правила', max_length=200)),
                ('description', models.TextField(help_text='Описание правила')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cms.importantsection')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImportantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Изображение', upload_to='important/')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.importantsection')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order'],
            },
        ),
    ]
