# Generated by Django 5.2.6 on 2025-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_dictionarycategory_split_two_columns'),
    ]

    operations = [
        # В базе колонка уже существует. Обновляем только состояние Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='city',
                    name='administrative_buildings',
                    field=models.TextField(blank=True, help_text='Описание административных зданий города', null=True, verbose_name='Административные здания'),
                ),
            ],
        ),
    ]
