# Generated by Django 5.2.6 on 2025-09-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_importantimage_page_importantrule_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantsection',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='important/hero/', verbose_name='Картинка секции'),
        ),
        migrations.AddField(
            model_name='importantsection',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt для картинки секции'),
        ),
        migrations.AddField(
            model_name='importantsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
    ]
