# Generated by Django 5.2.6 on 2025-09-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_remove_importantsection_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantsection',
            name='content',
            field=models.TextField(blank=True, verbose_name='Основной текст секции'),
        ),
        migrations.AddField(
            model_name='importantsection',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Для телефонов экстренной помощи', max_length=255, verbose_name='Подзаголовок'),
        ),
    ]
