# Generated by Django 5.2.6 on 2025-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_importantsection_content_importantsection_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantrule',
            name='rule_type',
            field=models.CharField(choices=[('passenger', 'Для пассажиров'), ('driver', 'Для водителей')], default='passenger', max_length=20, verbose_name='Тип правила'),
        ),
    ]
