# Generated by Django 5.2.6 on 2025-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_importantsection_driver_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='importantpage',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='importantpage',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Канонический URL'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='OG описание'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='important/og/', verbose_name='OG изображение'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='OG заголовок'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Переходить по ссылкам'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Индексировать поисковиками'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='twitter_description',
            field=models.TextField(blank=True, verbose_name='Twitter описание'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='twitter_image',
            field=models.ImageField(blank=True, upload_to='important/twitter/', verbose_name='Twitter изображение'),
        ),
        migrations.AddField(
            model_name='importantpage',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter заголовок'),
        ),
    ]
