# Generated by Django 5.2.6 on 2025-09-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_remove_importantpage_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCommunicationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_title', models.CharField(default='Интернет и мобильная связь', help_text='Основной заголовок страницы', max_length=255, verbose_name='Основной заголовок')),
                ('intro_text', models.TextField(blank=True, help_text='Текст в блоке с фоновым изображением', verbose_name='Вводный текст')),
                ('background_image', models.ImageField(blank=True, help_text='Фоновое изображение для вводного блока', upload_to='mobile_communication/background/', verbose_name='Фоновое изображение')),
                ('mobile_section_title', models.CharField(blank=True, default='Мобильная связь', max_length=255, verbose_name="Заголовок раздела 'Мобильная связь'")),
                ('internet_section_title', models.CharField(blank=True, default='Интернет', max_length=255, verbose_name="Заголовок раздела 'Интернет'")),
                ('seo_title', models.CharField(blank=True, help_text='SEO заголовок страницы', max_length=60)),
                ('seo_description', models.CharField(blank=True, help_text='SEO описание страницы', max_length=160)),
                ('seo_keywords', models.CharField(blank=True, help_text='SEO ключевые слова (через запятую)', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Канонический URL')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph заголовок', max_length=60)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph описание', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph изображение', upload_to='mobile_communication/og/')),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter Card заголовок', max_length=60)),
                ('twitter_description', models.CharField(blank=True, help_text='Twitter Card описание', max_length=160)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter Card изображение', upload_to='mobile_communication/twitter/')),
                ('robots_index', models.BooleanField(default=True, help_text='Разрешить индексацию')),
                ('robots_follow', models.BooleanField(default=True, help_text='Разрешить следование по ссылкам')),
            ],
            options={
                'verbose_name': "Страница 'Мобильная связь'",
                'verbose_name_plural': "Страница 'Мобильная связь'",
            },
        ),
        migrations.CreateModel(
            name='InternetProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название провайдера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website_url', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('logo_image', models.ImageField(blank=True, upload_to='mobile_communication/internet_providers/', verbose_name='Логотип')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_providers', to='cms.mobilecommunicationpage')),
            ],
            options={
                'verbose_name': 'Интернет провайдер',
                'verbose_name_plural': 'Интернет провайдеры',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MobileProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название оператора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website_url', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('logo_image', models.ImageField(blank=True, upload_to='mobile_communication/mobile_providers/', verbose_name='Логотип')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_providers', to='cms.mobilecommunicationpage')),
            ],
            options={
                'verbose_name': 'Мобильный оператор',
                'verbose_name_plural': 'Мобильные операторы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
