# Generated by Django 5.2.6 on 2025-09-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_mountainroutespage_mountainroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountainroute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mountainroute',
            name='site_label',
        ),
        migrations.RemoveField(
            model_name='mountainroute',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mountainroute',
            name='title',
        ),
    ]
