# Generated by Django 5.2.6 on 2025-09-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_mountainroute_name_mountainroute_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCommunicationsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_title', models.CharField(default='Транспортное сообщение республики Абхазия', max_length=255, verbose_name='Основной заголовок')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='transport_communications/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=60)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, upload_to='transport_communications/twitter/')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Страница 'Транспортное сообщение'",
                'verbose_name_plural': "Страница 'Транспортное сообщение'",
            },
        ),
        migrations.CreateModel(
            name='TransportBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('image_1', models.ImageField(blank=True, upload_to='transport_communications/blocks/', verbose_name='Первое изображение')),
                ('image_1_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для первого изображения')),
                ('image_2', models.ImageField(blank=True, upload_to='transport_communications/blocks/', verbose_name='Второе изображение')),
                ('image_2_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для второго изображения')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_blocks', to='cms.transportcommunicationspage')),
            ],
            options={
                'verbose_name': 'Транспортный блок',
                'verbose_name_plural': 'Транспортные блоки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
