# Generated by Django 5.2.6 on 2025-09-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_remove_transportblock_image_1_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_title', models.CharField(default='Вечеринки и яркие впечатления', max_length=255, verbose_name='Основной заголовок')),
                ('background_image', models.ImageField(blank=True, upload_to='parties/background/', verbose_name='Фоновое изображение баннера')),
                ('center_icon', models.ImageField(blank=True, upload_to='parties/icons/', verbose_name='Центральная иконка')),
                ('decor_image_1', models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 1')),
                ('decor_image_2', models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 2')),
                ('decor_image_3', models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 3')),
                ('decor_image_4', models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 4')),
                ('decor_image_5', models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 5')),
                ('intro_text_1', models.TextField(blank=True, help_text='Поддерживаются переносы строк', verbose_name='Первый текст баннера')),
                ('intro_text_2', models.TextField(blank=True, help_text='Поддерживаются переносы строк', verbose_name='Второй текст баннера')),
                ('intro_text_3', models.TextField(blank=True, help_text='Поддерживаются переносы строк', verbose_name='Третий текст баннера')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='parties/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=60)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, upload_to='parties/twitter/')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Страница 'Вечеринки'",
                'verbose_name_plural': "Страница 'Вечеринки'",
            },
        ),
        migrations.CreateModel(
            name='PartyCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
                ('slug', models.SlugField(help_text='Для идентификации в URL', unique=True, verbose_name='URL slug')),
                ('city_image', models.ImageField(blank=True, upload_to='parties/cities/', verbose_name='Изображение города')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cms.partiespage')),
            ],
            options={
                'verbose_name': 'Город для вечеринок',
                'verbose_name_plural': 'Города для вечеринок',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('date_info', models.CharField(blank=True, max_length=500, verbose_name='Информация о дате')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Местоположение')),
                ('description', models.TextField(blank=True, help_text='Поддерживаются переносы строк', verbose_name='Описание события')),
                ('event_url', models.URLField(blank=True, verbose_name='Ссылка на событие')),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cms.partycity')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['order', 'id'],
            },
        ),
    ]
