# Generated by Django 5.2.6 on 2025-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_partiespage_partycity_partyevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partiespage',
            name='intro_text_1',
        ),
        migrations.RemoveField(
            model_name='partiespage',
            name='intro_text_2',
        ),
        migrations.RemoveField(
            model_name='partiespage',
            name='intro_text_3',
        ),
        migrations.AddField(
            model_name='partiespage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Поддерживаются переносы строк', verbose_name='Текст баннера'),
        ),
        migrations.AlterField(
            model_name='partiespage',
            name='decor_image_1',
            field=models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 1 (слева сверху)'),
        ),
        migrations.AlterField(
            model_name='partiespage',
            name='decor_image_2',
            field=models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 2 (слева снизу)'),
        ),
        migrations.AlterField(
            model_name='partiespage',
            name='decor_image_3',
            field=models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 3 (центр снизу)'),
        ),
        migrations.AlterField(
            model_name='partiespage',
            name='decor_image_4',
            field=models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 4 (справа сверху)'),
        ),
        migrations.AlterField(
            model_name='partiespage',
            name='decor_image_5',
            field=models.ImageField(blank=True, upload_to='parties/decor/', verbose_name='Декоративное изображение 5 (справа снизу)'),
        ),
    ]
