# Generated by Django 5.2.6 on 2025-09-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_partyevent_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('video', 'Видео'), ('image', 'Изображение')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('media_file', models.FileField(help_text='Видео (.mp4) или изображение (.jpg, .png)', upload_to='parties/slider/', verbose_name='Медиа файл')),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='cms.partycity')),
                ('page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='cms.partiespage')),
            ],
            options={
                'verbose_name': 'Элемент слайдера',
                'verbose_name_plural': 'Элементы слайдера',
                'ordering': ['order', 'id'],
            },
        ),
    ]
