# Generated by Django 5.2.6 on 2025-09-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_partyslideritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalattraction',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='working_hours',
        ),
    ]
