# Generated by Django 5.2.6 on 2025-09-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_remove_culturalattraction_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalattraction',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Режим работы'),
        ),
    ]
