# Generated by Django 5.2.7 on 2025-10-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_accessibilityandtermspage_privacypolicypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, help_text='Логотип в футере', null=True, upload_to='footer/logo/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='', help_text='Описание под логотипом')),
                ('phone', models.CharField(blank=True, default='', help_text='Телефон', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Email', max_length=254)),
                ('address', models.TextField(blank=True, default='', help_text='Адрес')),
                ('copyright_text', models.CharField(blank=True, default='', help_text='Текст копирайта', max_length=255)),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('about', 'О нас'), ('services', 'Услуги'), ('legal', 'Правовая информация'), ('social', 'Социальные сети')], help_text='Категория ссылки', max_length=20)),
                ('label', models.CharField(help_text='Текст ссылки', max_length=255)),
                ('url', models.CharField(help_text='URL ссылки', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.footer')),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
