# Generated by Django 5.2.7 on 2025-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_footer_footerlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone',
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_info',
            field=models.TextField(blank=True, default='', help_text='Контактная информация (часы работы, телефон и т.д.)'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание сервиса (О сервисе)'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email для связи', max_length=254),
        ),
    ]
