# Generated by Django 5.2.7 on 2025-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_alter_footerlink_category_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslideritem',
            name='mobile_video',
            field=models.FileField(blank=True, help_text='Видео для мобильного приложения', null=True, upload_to='homepage/slider/mobile_videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='homeslideritem',
            name='video',
            field=models.FileField(blank=True, help_text='Видео для сайта', null=True, upload_to='homepage/slider/videos/%Y/%m/%d'),
        ),
    ]
