# Generated by Django 5.2.7 on 2025-11-01 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_homeslideritem_mobile_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsGymsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='sports_gyms/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=60)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, upload_to='sports_gyms/twitter/')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница спортивных залов',
                'verbose_name_plural': 'Страница спортивных залов',
            },
        ),
        migrations.CreateModel(
            name='SportsGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Режим работы')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('address_link', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='Контакты')),
                ('image', models.ImageField(blank=True, upload_to='sports_gyms/images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='cms.sportsgymspage')),
            ],
            options={
                'verbose_name': 'Спортивный зал',
                'verbose_name_plural': 'Спортивный зал',
                'ordering': ['order', 'id'],
            },
        ),
    ]
