# Generated by Django 5.2.7 on 2025-11-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_hometab_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometab',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Таб (верхнее меню сайта)', 'verbose_name_plural': 'Табы (верхнее меню сайта)'},
        ),
        migrations.RemoveField(
            model_name='hometab',
            name='platform',
        ),
        migrations.CreateModel(
            name='MobileHomeTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('about', 'Об Абхазии'), ('activities', 'Чем заняться'), ('booking', 'Запланируйте поездку'), ('essentials', 'Необходимо в поездке')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tabs', to='cms.homepage')),
            ],
            options={
                'verbose_name': 'Таб (мобильное приложение)',
                'verbose_name_plural': 'Табы (мобильное приложение)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
