# Generated by Django 5.2.7 on 2025-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_entertainmentcategory_importanttripcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutabkhaziacategory',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для API', max_length=100, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='entertainmentcategory',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для API', max_length=100, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='importanttripcategory',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для API', max_length=100, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='plantripcategory',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для API', max_length=100, verbose_name='Слаг'),
        ),
    ]
