# Generated by Django 5.2.7 on 2025-11-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_alter_aboutabkhaziacategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='music/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=60)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, upload_to='music/twitter/')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница музыки',
                'verbose_name_plural': 'Страница музыки',
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название трека')),
                ('artist', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('audio_file', models.FileField(help_text='MP3 файл', upload_to='music/tracks/%Y/%m/%d', verbose_name='Аудио файл')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='cms.musicpage')),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
