# Generated by Django 5.2.7 on 2025-11-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_musicpage_musictrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpage',
            name='intro_bg_image',
            field=models.ImageField(blank=True, help_text='Фоновая картинка для текста', upload_to='music/intro/', verbose_name='Фоновая картинка для текста'),
        ),
        migrations.AddField(
            model_name='musicpage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Текст под описанием музыки', verbose_name='Текст для музыки'),
        ),
        migrations.AddField(
            model_name='musicpage',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Основная картинка после текста', upload_to='music/main/', verbose_name='Основная картинка'),
        ),
    ]
