# Generated by Django 5.2.7 on 2025-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_hotspring_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportblock',
            name='location_link',
            field=models.URLField(blank=True, help_text='Ссылка на карту для заголовка', verbose_name='Ссылка на геолокацию'),
        ),
    ]
