# Generated by Django 5.2.9 on 2025-12-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0065_abkhaziancuisinepage_main_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionservice',
            name='contacts',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='excursionservice',
            name='contacts_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='excursionservice',
            name='contacts_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
