# Generated by Django 5.2.9 on 2025-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0066_alter_excursionservice_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryword',
            name='abkhazian',
            field=models.CharField(blank=True, help_text='Перевод на абхазском языке', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionaryword',
            name='abkhazian_en',
            field=models.CharField(blank=True, help_text='Перевод на абхазском языке', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryword',
            name='abkhazian_ru',
            field=models.CharField(blank=True, help_text='Перевод на абхазском языке', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryword',
            name='russian',
            field=models.CharField(blank=True, help_text='Перевод на русском языке', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionaryword',
            name='russian_en',
            field=models.CharField(blank=True, help_text='Перевод на русском языке', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryword',
            name='russian_ru',
            field=models.CharField(blank=True, help_text='Перевод на русском языке', max_length=500, null=True),
        ),
    ]
